# Generated by Django 2.0.6 on 2018-06-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=70)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('posted',),
            },
        ),
    ]
